### ISSUE TITLE
The .vim file is broken

### ISSUE THREAD

**Issue by galcohen-redislabs** [letorbi/vim-colors-modern-borland#2]
Getting the following error (when using `colorscheme borland` from the init.lua file):

```
~/.config/nvim/init
.lua:0../home/gal/.local/share/nvim/lazy/vim-colors-modern-borland/colors/borland.vim, line 265: Vim:E35: No previous regular expression
```

**Comment by letorbi** [comment]
Thanks for reporting. Apparently one of my latest updates introduced a bug. I've fixed a number of linting issues and it seems that the problem has been fixed now - at least on my system.

Please close the issue, if the problem has been solved on your system as well.
